### ISSUE TITLE
Jasmine tests on CircleCI don't allow block-scoped declarations

### ISSUE THREAD

**Issue by briandk** [briandk/transcriptase#25]
On my local machine, `npm test` with Jasmine runs fine.

[CircleCI builds fail][1] with this error:

```
> transcriptase@0.1.0 test /home/ubuntu/transcriptase
> jasmine

Started
F

Failures:
1) File saving behavior encountered a declaration exception
  Message:
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
  Stack:
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:374:25)
        at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
        at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
        at require (internal/module.js:12:17)
        at Suite.<anonymous> (/home/ubuntu/transcriptase/spec/fileSavingSpec.js:2:20)

1 spec, 1 failure
Finished in 0.008 seconds

npm ERR! Test failed.  See above for more details.

npm test returned exit code 1
```

[1]: https://circleci.com/gh/briandk/transcriptase/84?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by briandk** [comment]
I think this error was happening because we were using an older (2.5) version of Jasmine:

https://github.com/briandk/transcriptase/blob/6c2bcd67098f469e06334d16265275cea28a62bc/package.json#L64-L66

I think that older version was spec'ed because I assumed the latest version of jasmine was at the top of the versions list; not the bottom.

<img width="962" alt="2017-09-30-confusing-old-and-new-versions-of-jasmine 09-30-17 5 39 12 pm" src="https://user-images.githubusercontent.com/330036/31049700-46fed068-a606-11e7-921a-285c2b2e33f1.png">

When we upgraded to 2.7/2.8, I think the problem went away.
